# Generated by Django 5.1.1 on 2024-09-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'التصنيف', 'verbose_name_plural': 'التصنيف'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'مشروع', 'verbose_name_plural': 'مشروع'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'مهمة', 'verbose_name_plural': 'مهمة'},
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'قيد التنفيذ'), (2, 'مكتمل'), (3, 'معلق'), (4, 'ملغى')], default=1),
        ),
    ]
